### ISSUE TITLE
Lägg till text om att anonyma hänvisas till telefon

### ISSUE THREAD

**Issue by perber14** [malmostad/sv-contact-portlet#1]
Det behövs en liten text i formuläret som informerar besökaren om att anonymitet inte kan garanteras om formuläret används:

Kravspec:

1. Texten ska vara "Vill du vara anonym rekommenderar vi att du istället kontaktar oss per telefon."
2. Texten ska ligga mellan input-rutan för "Meddelande" och knappen "Skicka in ditt meddelande"
3. Texten ska ha en ram med en röd list för att tydligt synas (som nedan, fast röd list): 

![image](https://cloud.githubusercontent.com/assets/22030097/24459109/0b44e302-149b-11e7-89c7-d369d6488348.png)

**Comment by tomasrobertsson** [comment]
Har du en länk till en sida, på test, där denna text ska in?

**Comment by perber14** [comment]
Du kan lägga det på vilken sida som helst som har "Skriv till oss" i test-miljön!

**Comment by magnivar** [comment]
t.ex. http://www.test.malmo.se/Bo-bygga--miljo/Livsmedelskontroll/Anmal-misstankt-matforgiftning.html

Klicka på Skriv till oss

**Comment by tomasrobertsson** [comment]
Och för att vara tydliga:
Den ska visas för alla kontaktformulär på malmo.se men inte på komin.malmo.se
Det som avgör om den ska visas eller ej är vilket sajt de ligger på eller ska det vara annat villkor som tar fram texten?

**Comment by perber14** [comment]
Den ska finnas med i alla kontaktformulären på malmo.se.

**Comment by magnivar** [comment]
@tomasrobertsson Här måste vi vidare...

**Comment by tomasrobertsson** [comment]
Uppfattat. Jag tittar på det mer eller mindre omgående.

**Comment by tomasrobertsson** [comment]
Ta gärna en titt på sidan ovan, eller annan med kontaktruta på malmö test. 
Nu ligger det en som ser ut som ser ut som:
![bild](https://user-images.githubusercontent.com/15670239/29969413-50d23f50-8f20-11e7-9073-30ddfb1c023e.png)

Jag har här tagit formateringsregler från Global assets och uppdaterat dem i Sitevision assets. I sig borde denna CSS-regel ligga där men det är där jag kan göra något. 
Ser detta bra ut kan jag göra detta redo för deploy på produktion

**Comment by Svempan** [comment]
Föreslår att texten istället är:
"Vill du **vara säker på att** vara anonym rekommenderar vi att du istället kontaktar oss per telefon."

**Comment by tomasrobertsson** [comment]
Ok, det kan jag ändra om ni säger så. Ser dialogen ut som ni önskar i övrigt?

**Comment by perber14** [comment]
Jag funderade ett slag. Det blir lättare svenska om vi till och med istället tar:

"Vill du vara säker på att vara anonym rekommenderar vi att du istället ringer till oss." Aktivt och mer direkt språk. @Svempan, ok?

**Comment by perber14** [comment]
@tomasrobertsson I övrigt toppen! Vi bara inväntar Svens svar på min senaste kommentar om ytterligare språkändring!

**Comment by Svempan** [comment]
OK ;-)

**Comment by perber14** [comment]
Dåså, @tomasrobertsson! Ändra texten till:

"Vill du vara säker på att vara anonym rekommenderar vi att du istället ringer till oss."

**Comment by tomasrobertsson** [comment]
Det ordnar jag och lägger ut på test för "final review" senare idag.

**Comment by tomasrobertsson** [comment]
Ger ni OK på deploy av denna på malmo.se extern webb? 
Med denna deploy kommer även ändringen från Stadsområden till Områden med. Verifiera gärna även denna. 
 @perber14  och @Svempan

**Comment by perber14** [comment]
@tomasrobertsson Denna är OK för produktionssättning. Kolla dock med @magnivar innan du deployar, så att alla som behöver veta är med på banan. Tack!

**Comment by magnivar** [comment]
Deployad och klar
